CREATE TABLE NILAI_IPA(
    ID INT PRIMARY KEY,
	ROW_NISN REFERENCES SISWA(NISN) NOT NULL,
	NILAI_BIOLOGI NOT NULL,
	NILAI_FISIKA NOT NULL,
	NILAI_KIMIA NOT NULL,
	NILAI_MATEMATIKA NOT NULL
);

CREATE TABLE NILAI_IPS(
    ID INT PRIMARY KEY,
	ROW_NISN REFERENCES SISWA(NISN) NOT NULL,
	NILAI_GEOGRAFI NOT NULL,
	NILAI_SOSIOLOGI NOT NULL,
	NILAI_EKONOMI NOT NULL,
	NILAI_SEJARAH NOT NULL
);

CREATE TABLE NILAI_UMUM(
    ID INT PRIMARY KEY,
	ROW_NISN REFERENCES SISWA(NISN) NOT NULL,
	NILAI_PENJASKES NOT NULL,
	NILAI_BAHASA_INGGRIS NOT NULL,
	NILAI_BAHASA_INDONESIA NOT NULL,
	NILAI_PKN NOT NULL,
	NILAI_SENI_BUDAYA NOT NULL
);

